#!/bin/sh

# This is example. content of the termbar is up to you.
# Please share your ideas. :)

red='\033[0;31m'
rst='\033[0m'

while true; do
	date=$(date +"%A, %B %d - %H:%M")
	user=$(whoami)
	# Random lines from my openbsd and related cheatsheet 
	# I want to remember
	memos=$(cat /home/"$user"/work/openbsd/memoize | sort -R | head -n1)
	terms=$(ps -c -U "$user" | grep -c st)
	sshs=$(ps -c -U "$user" | grep -c ssh$)
	#part=$(df -h | tail -n+2 | awk '{print $6 " " $5}' | paste -s - | tr '\t' ' ')
	cpu=$(sysctl hw.sensors.cpu0.temp0 | cut -d "=" -f 2 | cut -d "." -f 1)
	vol=$((`mixerctl -n outputs.master|cut -f 1 -d ','`*100/255))

	printf "${red}cwm${rst} %-210s terms:%s | sshs:%s | vol: %s%% | cpu: %s° | %s\\r" \
		"$memos" "$terms" "$sshs" "$vol" "$cpu" "$date"

	sleep 5
done

