#!/bin/sh

# This is example. Content of the termbar is up to you.
# Please share your setup. :)

# Some people like colors
red='\033[0;31m'
rst='\033[0m'

while true; do
	DATE=$(date +"%A, %B %d - %H:%M")

	# Random lines from my openbsd and related cheatsheet 
	# I want to remember
	MEMO=$(sort -R /home/"$USER"/work/openbsd/memoize | head -n1)

	# Don't exit WM while something important is running on workspaces
	NVI=$(pgrep -u "$USER" nvi$ | wc -l | tr -d ' ')
	TERMS=$(pgrep -u "$USER" st$ | wc -l | tr -d ' ')
	SSHS=$(pgrep -u "$USER" ssh$ | wc -l | tr -d ' ')

	# - 
	CPU=$(sysctl -n hw.sensors.cpu0.temp0 | cut -d. -f1)

	printf "  ${red}cwm${rst} %-239s  nvis: %s  terms: %s  sshs: %s  cpu: %s°  %s\\r" \
		"$MEMO" "$NVI" "$TERMS" "$SSHS" "$CPU" "$DATE"

	sleep 5
done

