#!/bin/sh

while true; do
        CPU_SPEED=$(sysctl hw.cpuspeed | cut -d "=" -f 2 | cut -d "." -f 1)
        CPU_TEMP=$(sysctl hw.sensors.cpu0.temp0 | cut -d "=" -f 2 | cut -d "." -f 1)
        RAM=$(top | grep Memory | awk {'print $3'})
        BAT_STATUS=$(sysctl hw.sensors.acpiac0.indicator0 | cut -d "=" -f 2 | cut -d "." -f 1)
        BAT=$(apm -l)
        DATE=$(date)
        NWID=$(ifconfig | grep ieee | awk {'print $3'})
        IP=$(dig +short myip.opendns.com @resolver1.opendns.com)
        echo -en "  $USER | $DATE | CPU: $CPU_SPEED - $CPU_TEMP° | Ram: $RAM | Bat: $BAT - \
                $BAT_STATUS | Nwid: $NWID | Public IP: $IP\r"
        sleep 1
done
